/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Produto;
import Model.Categoria;
import Model.Cliente;
import Model.Endereco;
import Model.Funcionario;
import Model.Mercado;
import view.TelaCadastroCategoria;

/**
 *
 * @author Nicolas
 */
public class SistemaFuncionarioView extends javax.swing.JFrame {

    /**
     * Creates new form InicioFuncionarioView
     */
    public SistemaFuncionarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miListarProdutos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        miCadCategoria = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Inicial");

        jMenu1.setText("Estoque");

        miListarProdutos.setText("Listar produtos");
        miListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(miListarProdutos);

        jMenuItem2.setText("Cadastrar produto");
        jMenu1.add(jMenuItem2);

        miCadCategoria.setText("Cadastrar categoria");
        miCadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(miCadCategoria);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cliente");

        jMenuItem4.setText("Listar clientes");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pedido");

        jMenuItem5.setText("Listar pedidos");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarProdutosActionPerformed
        ListarProdutosView listarProdutos = new ListarProdutosView();
        listarProdutos.setVisible(true);
    }//GEN-LAST:event_miListarProdutosActionPerformed

    private void miCadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadCategoriaActionPerformed
        TelaCadastroCategoria telaCadCategoria = new TelaCadastroCategoria();
        telaCadCategoria.setVisible(true);
    }//GEN-LAST:event_miCadCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem miCadCategoria;
    private javax.swing.JMenuItem miListarProdutos;
    // End of variables declaration//GEN-END:variables
}
