/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Produto;
import Model.Categoria;
import Model.Mercado;

/**
 *
 * @author Nicolas
 */
public class SistemaFuncionarioView extends javax.swing.JFrame {

    /**
     * Creates new form InicioFuncionarioView
     */
    public SistemaFuncionarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCliente = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miListarProdutos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        miCadCategoria = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miCadCliente = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Inicial");

        btCliente.setText("Cliente");
        btCliente.setToolTipText("");
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });

        jMenu1.setText("Estoque");

        miListarProdutos.setText("Listar produtos");
        miListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(miListarProdutos);

        jMenuItem2.setText("Cadastrar produto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        miCadCategoria.setText("Cadastrar categoria");
        miCadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(miCadCategoria);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cliente");

        miCadCliente.setText("Cadastrar Cliente");
        miCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadClienteActionPerformed(evt);
            }
        });
        jMenu2.add(miCadCliente);

        jMenuItem4.setText("Listar clientes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pedido");

        jMenuItem5.setText("Listar pedidos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(502, Short.MAX_VALUE)
                .addComponent(btCliente)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(420, Short.MAX_VALUE)
                .addComponent(btCliente)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarProdutosActionPerformed
        TelaListagemProdutos listarProdutos = new TelaListagemProdutos();
        listarProdutos.setVisible(true);
    }//GEN-LAST:event_miListarProdutosActionPerformed

    private void miCadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadCategoriaActionPerformed
        TelaCadastroCategoria telaCadCategoria = new TelaCadastroCategoria();
        telaCadCategoria.setVisible(true);
    }//GEN-LAST:event_miCadCategoriaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaCadastroProduto telaCadProduto = new TelaCadastroProduto();
        telaCadProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void miCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadClienteActionPerformed
        TelaCadastroCliente telaCadCliente = new TelaCadastroCliente();
        telaCadCliente.setVisible(true);
    }//GEN-LAST:event_miCadClienteActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaListagemCliente telaListCliente = new TelaListagemCliente();
        telaListCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        SistemaClienteView sisClienteView = new SistemaClienteView();
        sisClienteView.setVisible(true);
    }//GEN-LAST:event_btClienteActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TelaListaPedidos telaPedidos = new TelaListaPedidos();
        telaPedidos.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaFuncionarioView().setVisible(true);
            }
        });
        
        Mercado mercado = Mercado.getMercado();
        
        Categoria c1 = new Categoria("Alimento", "Pereciveis");
        Categoria c2 = new Categoria("Higiene", "Higiene pessoal");
        Categoria c3 = new Categoria ("Limpeza", "Produtos de limepza");
        Categoria c4 = new Categoria ("Frios e lacticínios", "");
        
        mercado.getCategorias().add(c1);
        mercado.getCategorias().add(c2);
        mercado.getCategorias().add(c3);
        mercado.getCategorias().add(c4);
        
        Produto p1 = new Produto("Arroz", 17.0, "1KG", c1, 10);
        Produto p2 = new Produto("Desodorante", 8.0, "Rexona", c2, 8);
        Produto p3 = new Produto("Sabão", 15.0, "OMO 1KG", c3, 13);
        Produto p4 = new Produto("Leite Vida Longe", 3.75, "1L", c4, 50);
        Produto p5 = new Produto("Margarina Qualidade", 13.50, "1KG", c4, 57);
        Produto p6 = new Produto("Iogurte Charmanito", 3.75, "200ml", c4, 43);
        Produto p7 = new Produto("Alcool Fogarel", 8.90, "1L", c3, 42);
        Produto p8 = new Produto("Detergente IP", 2.50, "500ml", c3, 89);
        Produto p9 = new Produto("Sabonete Donivea", 6.75, "1L", c2, 13);
        Produto p10 = new Produto("Maçã Turma da Nomica", 5.75, "Preço por KG", c2, 12);
        
        mercado.getEstoque().addProduto(p1.getCodigo(), p1);
        mercado.getEstoque().addProduto(p2.getCodigo(), p2);
        mercado.getEstoque().addProduto(p3.getCodigo(), p3);
        mercado.getEstoque().addProduto(p4.getCodigo(), p4);
        mercado.getEstoque().addProduto(p5.getCodigo(), p5);
        mercado.getEstoque().addProduto(p6.getCodigo(), p6);
        mercado.getEstoque().addProduto(p7.getCodigo(), p7);
        mercado.getEstoque().addProduto(p8.getCodigo(), p8);
        mercado.getEstoque().addProduto(p9.getCodigo(), p9);
        mercado.getEstoque().addProduto(p10.getCodigo(), p10);
         
        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCliente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem miCadCategoria;
    private javax.swing.JMenuItem miCadCliente;
    private javax.swing.JMenuItem miListarProdutos;
    // End of variables declaration//GEN-END:variables
}
