/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Categoria;
import Model.Cliente;
import Model.Endereco;
import Model.Funcionario;
import Model.Mercado;
import Model.Produto;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicolas
 */
public class TelaLogin extends javax.swing.JFrame {

    private List<Cliente> clientes;
    private List<Funcionario> funcionarios;
    
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        Mercado mercado = Mercado.getMercado();
        this.clientes = mercado.getClientes();
        this.funcionarios = mercado.getFuncionarios();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsuarioLogin = new javax.swing.JTextField();
        pfSenhaUsuario = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Usuário");

        jLabel2.setText("Senha");

        btLogin.setText("Entrar");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfUsuarioLogin)
                                .addComponent(pfSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(pfSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btLogin)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        String usuario = tfUsuarioLogin.getText();
        String senha = String.valueOf(pfSenhaUsuario.getPassword());
        
        for (Cliente cli : this.clientes){
            boolean valida = cli.validaLogin(usuario, senha);
            if(valida == true){
                
                JOptionPane.showMessageDialog(this, "Sucesso no login!");
                
            }
        }
        
        for (Funcionario fun : this.funcionarios){
            boolean valida = fun.validaLogin(usuario, senha);
            if(valida == true){
                
                SistemaFuncionarioView sistemaFuncionarioView = new SistemaFuncionarioView();
                sistemaFuncionarioView.setVisible(true);
                
                this.dispose();
                
            }
        }
    }//GEN-LAST:event_btLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
        
        Mercado mercado = Mercado.getMercado();
        
        Categoria c1 = new Categoria("Alimento", "Pereciveis");
        Categoria c2 = new Categoria("Higiene", "Higiene pessoal");
        Categoria c3 = new Categoria ("Limpeza", "Produtos de limepza");
        
        Produto p1 = new Produto("Arroz", 10.0, "Saco de 1KG", c1, 10);
        Produto p2 = new Produto("Desodorante", 10.0, "Rexona", c2, 8);
        Produto p3 = new Produto("Sabão", 10.0, "OMO 1KG", c3, 13);
        
        mercado.getEstoque().addProduto(p1.getCodigo(), p1);
        mercado.getEstoque().addProduto(p2.getCodigo(), p2);
        mercado.getEstoque().addProduto(p3.getCodigo(), p3);
        
        Endereco e1 = new Endereco("Rua dos bobos", "Centro", 89140000, 0); 
        
        Funcionario f1 = new Funcionario("Repositor de estoque", "jurandir", 
                "026.130.490-90", "01/10/1999", 999999999, e1, "jurandir", 
                "123");
        
        Funcionario f2 = new Funcionario("Gerente", "Fernando", 
                "025.142.560-75", "27/11/1980", 999999999, e1, "fernando", 
                "132");
        
        Funcionario f3 = new Funcionario("Caixa", "Amanda", 
                "087.232.780-82", "30/12/2001", 999999999, e1, "amandaCaixa", 
                "301201");
        
        Cliente cl1 = new Cliente("Jaspion", "087.232.780-82", "13/10/1970", 
                999999999, e1, "jaspion", "jaspion132");
        
        Cliente cl2 = new Cliente("Donald", "087.232.780-82", "13/10/1960", 
                999999999, e1, "donaldinho", "patopato2030");
        
        mercado.getFuncionarios().add(f1);
        mercado.getFuncionarios().add(f2);
        mercado.getFuncionarios().add(f3);
        
        mercado.getClientes().add(cl1);
        mercado.getClientes().add(cl2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pfSenhaUsuario;
    private javax.swing.JTextField tfUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
